name: deploy
on:
  push:
    branches:
      - prod
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: macbre/push-to-ghcr@master
      with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  publish-phoenix-website-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: phoenix-nsec
          password: ${{ secrets.TOKEN }}
      - name: Build the phoenix-website Docker image
        run: |
          docker build . --tag ghcr.io/phoenix-nsec/phoenix-website:latest
          docker push ghcr.io/phoenix-nsec/phoenix-website:latest
