name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish-phoenix-website-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
      - name: Build the phoenix-website Docker image
        run: |
          docker build . --tag ghcr.io/Phoenix-NSEC/phoenix-website:latest
          docker run ghcr.io/Phoenix-NSEC/phoenix-website:latest
          docker push ghcr.io/Phoenix-NSEC/phoenix-website:latest